
# Training configuration
seed: 31
max_len: 4096
learning_rate: 0
batch_size: 40 #160
accelerator: gpu
devices: 2

# Model configuration
JambaConfig:
  vocab_size: 9
  tie_word_embeddings: False
  hidden_size: 384
  intermediate_size: 24
  num_hidden_layers: 12
  num_attention_heads: 16
  num_key_value_heads: 16
  pad_token_id: 3
  bos_token_id: 0
  eos_token_id: 1
  num_experts: 8
  expert_layer_period: 2
  expert_layer_offset: 1
  attn_layer_period: 8
  attn_layer_offset: 4
  use_mamba_kernels: True
  mamba_d_state: 16
  mamba_d_conv: 4
  mamba_expand: 2
  mamba_dt_rank: auto

# Data path and output directories
data_file: /home/reagan/Projects/RNA_optimization/model/models_put_on_github/data/generalization_data/icodon_specie_h.csv
finetuned_model_path: /home/reagan/Projects/RNA_optimization/model/models_put_on_github/barplot/compare_other_models/our_model/3fold_utr_finetune_early_stopping/run_0/epoch=34_step=6265_train_loss=0.3330895603_val_loss=9.9434829894_run0.ckpt
