seed: 31
batch_size: 300
beam_width: 50
beta: 30
theta: 20 # theta * CAI
patience: 10
max_steps: 100 #500
start_from_protein: False
partial_sampling_percentage: 0.5

utr5: GAATAAACTAGTATTCTTCTGGTCCCCACAGACTCAGAGAGAACCCGCCACC
utr3: TGATAGTAATGACTCGAGCTGGTACTGCATGCACGCAATGCTAGCTGCCCCTTTCCCGTCCTGGGTACCCCGAGTCTCCCCCGACCTCGGGTCCCAGGTATGCTCCCACCTCCACCTGCCCCACTCACCACCTCTGCTAGTTCCAGACACCTCCCAAGCACGCAGCAATGCAGCTCAAAACGCTTAGCCTAGCCACACCCCCACGGGAAACAGCAGTGATTAACCTTTAGCAATAAACGAAAGTTTAACTAAGCTATACTAACCCCAGGGTTGGTCAATTTCGTGCCAGCCACACCCTGGAGCTAGCGCGGCCGCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGCAATTGACTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
cds: atgggagtgaaagttctttttgcccttatttgtattgctgtggccgaggccaaaccaactgaaaacaatgaagatttcaacattgtagctgtagctagcaactttgctacaacggatctcgatgctgaccgtggtaaattgcccggaaaaaaattaccacttgaggtactcaaagaaatggaagccaatgctaggaaagctggctgcactaggggatgtctgatatgcctgtcacacatcaagtgtacacccaaaatgaagaagtttatcccaggaagatgccacacctatgaaggagacaaagaaagtgcacagggaggaataggagaggctattgttgacattcctgaaattcctgggtttaaggatttggaacccatggaacaattcattgcacaagttgacctatgtgtagactgcacaactggatgcctcaaaggtcttgccaatgtgcaatgttctgatttactcaagaaatggctgccacaaagatgtgcaacttttgctagcaaaattcaaggccaagtggacaaaataaagggtgccggtggtgattaa



distill_model_path: ./14M_stage2_distilled_finetuend_on_human_mouse.ckpt
full_model_path: ./14M_stage2_finetuned_on_human_mouse.ckpt

result_save_path: <Path to directory that you want to save sequences are checked>


vocab_size: 9
distill_JambaConfig:
  vocab_size: 9
  tie_word_embeddings: False
  hidden_size: 128
  intermediate_size: 8
  num_hidden_layers: 8
  num_attention_heads: 8
  num_key_value_heads: 8
  pad_token_id: 3
  bos_token_id: 0
  eos_token_id: 1
  num_experts: 7
  expert_layer_period: 2
  expert_layer_offset: 1
  attn_layer_period: 8
  attn_layer_offset: 4
  use_mamba_kernels: True
  mamba_d_state: 9
  mamba_d_conv: 4
  mamba_expand: 2
  mamba_dt_rank: auto
  

full_JambaConfig:
  vocab_size: 9
  tie_word_embeddings: False
  hidden_size: 384
  intermediate_size: 24
  num_hidden_layers: 12
  num_attention_heads: 16
  num_key_value_heads: 16
  pad_token_id: 3
  bos_token_id: 0
  eos_token_id: 1
  num_experts: 8
  expert_layer_period: 2
  expert_layer_offset: 1
  attn_layer_period: 8
  attn_layer_offset: 4
  use_mamba_kernels: True
  mamba_d_state: 16
  mamba_d_conv: 4
  mamba_expand: 2
  mamba_dt_rank: auto
  